# Generated by Django 6.0.3 on 2026-03-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.workout'),
        ),
        migrations.AlterField(
            model_name='session',
            name='workout_type',
            field=models.CharField(choices=[('Bodyweight Workouts', 'Bodyweight Workouts'), ('Cardio', 'Cardio'), ('HIIT', 'HIIT'), ('Yoga', 'Yoga'), ('Dumbell workouts', 'Dumbell workouts')], max_length=100),
        ),
    ]
