# Generated by Django 6.0.3 on 2026-03-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_session_workout_alter_session_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.plan'),
        ),
    ]
