# Generated by Django 6.0.3 on 2026-03-26 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_session_client_alter_session_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_client_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
