# Generated by Django 6.0.3 on 2026-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_session_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='followed_trainers',
        ),
    ]
