# Generated by Django 6.0.3 on 2026-03-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_clientprofile_followed_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.clientprofile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.trainerprofile'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.trainerprofile'),
        ),
    ]
