# Generated by Django 6.0.3 on 2026-03-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_customuser_is_client_customuser_is_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.trainerprofile'),
        ),
    ]
