# Generated by Django 6.0.3 on 2026-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_session_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
