# Generated by Django 6.0.3 on 2026-03-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_session_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.clientprofile'),
        ),
    ]
