# Generated by Django 6.0.3 on 2026-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_session_title_alter_session_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
