# Generated by Django 6.0.3 on 2026-03-27 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_membershipplan_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
